[package]
name = "tetriche"
version = "0.1.0"
edition = "2021"
author = ["Nicolas Rybowski", "Quentin De Coninck"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
